article/urls.py
from django.conf.urls import patterns, include, url
from .views import (articles, article, language, create, like_article,
 					add_comment, search_titles)
from .api import ArticleResource

# creating an instance
article_resource = ArticleResource()

urlpatterns =[
	url(r'^all/$', articles),
	url(r'^get/(?P<article_id>\d+)/$',article),
	url(r'^language/(?P<language>[a-z\-]+)/$',language),
	url(r'^create/$',create),
	url(r'^like/(?P<article_id>\d+)/$',like_article),
	url(r'^add_comment/(?P<article_id>\d+)/$',add_comment),
	url(r'^search/$', search_titles),
	url(r'^api/', include(article_resource.urls)),
	]

django_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import (login, auth_view, logout, loggedin, 
    invalid_login, register_success, register_user, ContactWizard)
from .views import ContactForm1,ContactForm2,ContactForm3
from .settings import DEBUG
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/',include('article.urls')),
    url(r'^accounts/',include('userprofile.urls')),
    url(r'^accounts/login/$',login),
    url(r'^accounts/auth/$',auth_view),
    url(r'^accounts/logout/$',logout),
    url(r'^accounts/loggedin/$',loggedin),
    url(r'^accounts/invalid/$',invalid_login),
    url(r'^accounts/invalid/$',invalid_login),
    url(r'^accounts/register/$',register_user),
    url(r'^accounts/register_success/$',register_success),
    url(r'^contact/$',ContactWizard.as_view([ContactForm1,ContactForm2,ContactForm3])),
]

# 5.10
if not DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

article/models.py
from __future__ import unicode_literals
from django.db import models
import datetime
from time import time
from django_test.settings import UPLOAD_FILE_PATTERN, DEBUG

# for the thumbnail upload
def get_upload_file_name(instance, filename):
	# return "uploaded_files/{}_{}".format(str(time()).replace('.','_'), filename)
	return UPLOAD_FILE_PATTERN % (str(time()).replace('.','_'), filename)

# Create your models here.
class Article(models.Model):
	# 200 characters
	title = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published', blank=True, null=True)
	'''
	 # default=datetime.date.today(),
	 # when i do default above, the create articles website works fine, 
	 # however, the admin create admin doesnt work
	 '''
	likes = models.IntegerField(default=0) 

	# ADD THUMBNAIL, used tastypie to migrate
	thumbnail = models.FileField(upload_to=get_upload_file_name, blank=True, null=True)
	# get_upload_file_name is a function that you create, because you can perform some logic like account authorization


	def __unicode__(self):
		return self.title
	
	# for testing views
	def get_absolute_url(self):
		return "/articles/get/%i/" %self.id
		# it returns a string that tells us what we consider a proper url for an article could be

	def get_thumbnail(self):
		thumb = str(self.thumbnail)
		if not DEBUG:
			thumb = thumb.replace('assets/','')
		return thumb

class Comment(models.Model):

	name = models.CharField(max_length=200)
	# first_name = models.CharField(max_length=200)
	# second_name = models.CharField(max_length=200)

	body = models.TextField()
	pub_date = models.DateTimeField('date published')
	# established relationship
	# for more google django models 
	article = models.ForeignKey(Article)
	# this means article sis relatred to Article class

	def __unicode__(self):
		return self.name

article/forms.py
from django import forms
from .models import Article, Comment
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm 
# from django.core.exceptions import ValidationError

class ArticleForm(forms.ModelForm):
	# ModelForm is a form made to deal with models specifically

	class Meta:
		# this adds an extra bit of information
		# define anything that isnt actually a form field
		model = Article
		fields = ('title','body','pub_date','thumbnail')

	
class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('name', 'body')

article/views.py
from django.shortcuts import render_to_response
from article.models import Article, Comment
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ArticleForm, CommentForm
from django.template.context_processors import csrf
from django.utils import timezone
# Create your views here.

def articles(request):
	''' EVERY VIEW FUNCTION NEEDS A REQUEST 
	sends all articles to the home page, articles.html'''


	language = "en-us"
	session_language = "en-us"

	if "lang" in request.COOKIES:
		language = request.COOKIES["lang"]

	if "lang" in request.session:
		session_language = request.session["lang"]

	args = {}
	args.update(csrf(request))
	# this was added for ajax call

	args['articles'] = Article.objects.all()
	args['language'] = language
	args['session_language'] = session_language 

	return render_to_response('articles.html',args)

def article(request, article_id=1):
	'''sends the requested (GET) article to a different page'''
	return render_to_response('article.html',{'article': Article.objects.get(id=article_id)})


def language(request, language="en-us"):
	response = HttpResponse("setting language to %s" %language)
	response.set_cookie("lang", language)
	request.session["lang"] = language
	return response

def create(request):
	if request.POST:
		# prevents hacking from url(GET method)
		form = ArticleForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/articles/all')
	else:
		form = ArticleForm()

	args = {}
	args.update(csrf(request))
	args['form'] = form
	return render_to_response('create_article.html',args)

def like_article(request, article_id=1):
	'''UPDATING THE DATABASE
	this is for liking the article'''
	if article_id:
		a = Article.objects.get(id=article_id)
		count = a.likes
		count += 1
		a.likes = count
		a.save()

	return HttpResponseRedirect('/articles/get/%s' %article_id)

def add_comment(request, article_id=1):
	# a is the article object
	a = Article.objects.get(id=article_id)
	# post it to the corresponding article
	if request.method=="POST":
		# f is the comment form
		f = CommentForm(request.POST)
		if f.is_valid():
			# to establish the rel b/w comment and the article make and instance "C" but dont save it yet
			c = f.save(commit=False)
			# cis the comment object
			c.pub_date = timezone.now()
			c.article = a
			c.save()
			# now the rel is established and saved in c object
			return HttpResponseRedirect('/articles/get/%s' %article_id)
	else:
		# send nothing to CommentForm modelForm
		f = CommentForm()

	# to have our form protected add CSRF
	args = {}
	args.update(csrf(request))

	# what do you wanna pass through to the template?
	# article and form
	args['article'] = a
	args['form'] = f

	return render_to_response('add_comment.html', args)

def search_titles(request):
	if request.method =="POST":
		search_text = request.POST['search_text']
	else:
		search_text = ''

	articles= Article.objects.filter(title__contains=search_text)
	return render_to_response('ajax_search.html',
		{'articles':articles})

article/templates/add_comment.html
{% extends "base.html" %}
{% load staticfiles %}

{% block sidebar %}
			<ul>
				<li><a href="/articles/get/{{article.id}}">Cancel</a></li>
			</ul>
{% endblock %}

{% block container %}
	<form action="/articles/add_comment/{{article.id}}/" method="POST">{% csrf_token %}
		<ul>
			{{form.as_ul}}
		</ul>
		<input type="submit" name="submit" value="Post COmment"></input>

	</form>
{% endblock %}

article/templates/ajax_search.html
{% if articles.count > 0 %}

	{% for article in articles %}
		<li>
			<a href="/articles/get/{{article.id}}">{{article.title}}</a>
		</li>
	{% endfor %}

{% else %}

	<li>Nothing to show!</li>

{% endif %}

article/templates/article.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- {% load static %} -->

{% block sidebar %}
			<ul>
				<li><a href="/articles/all">Articles</a></li>
			</ul>
{% endblock %}

{% block container %}

<h2>{{ article.title }}</h2>
<p> {{ article.body }} </p>

{% if article.thumbnail %}
<!-- href="{% static "css/style.css" %} -->
	<p>
		<!-- <img src="/static/{{article.thumbnail}}/" width="200" /> -->
		<!-- 5.9  {% get_static_prefix %} -->
		<img src="{% get_static_prefix %}{{article.get_thumbnail}}" width="200">
	</p>
{% endif %}


<!-- LIKES -->
<p> {{article.likes}} people liked this article </p>
<p><a href="/articles/like/{{article.id}}">Like</a></p>

<h2>Comments</h2>
<!-- this for loops displays any comments on the article -->
<!-- because comment has a foregnkey relationship with article it has a set of comments-->
{% for c in article.comment_set.all %}
<p>{{c.name}}: {{c.body}}</p>
{% endfor %}

<!-- takes you to a new webpage with a form to add comments -->
<p><a href="/articles/add_comment/{{article.id}}">Add Comment</a></p>

{% endblock %}

article/templates/articles.html
{% extends "base.html" %}
{% load staticfiles %}
{% load article_tags %}

{% block sidebar %}
		<ul>
			<li><a href="/articles/all">Articles</a></li>
			<li><a href="/articles/create">Create Articles</a></li>
			<li><a href="/admin/">Admin</a></li>
			<li><a href="/accounts/register">Register</a></li>
			<li><a href="/accounts/login">LogIn</a></li>
		</ul>
		
<!-- for AJAX -->
		<h3>Search</h3>
		{% csrf_token %}
		<input type="text" id="search" name="search" />
		<ul id="search-results">
			
		</ul>
{% endblock %}

{% block container %}

<h2> Language is: {{language}} </h2>
<h2> Session Language is: {{session_language}} </h2>
{% for article in articles %}
	<h4><a href='/articles/get/{{article.id}}/'>{{article.title}}</a></h4>
	<p>{{ article.body|lower|article_shorten_body:50 }}</p>
	<!-- truncatewords:"10"
	change lower to upper changes the article desc to UPPERCASE -->
	<p> {{article.likes}} people liked this article </p>
{% endfor %}
{% endblock %}

article/templates/contact_form.html
{% extends 'base.html' %}
{% block container %}

<h2>Contact Us</h2>
<p>
	<!-- this tells us how many steps are available inside of the wizard
	because the wizard passes an instance of the variable called the wizard 
	u could have step 0,
	the form count is dependent upon the forms we put in the urls section.  -->
	Step {{wizard.steps.step1}} of {{wizard.steps.count}}
</p>
	<!-- few validation errors -->
	{% for field in form %}
		{{field.error}}
	{% endfor %}

	<form action="/contact/" method="post">{% csrf_token %}
	<table>
	<!-- the main instance of the current form -->
	{{wizard.management_form}}
	<!-- if there are multiple forms, in our case we dont -->
	{% if wizard.form.forms %} 
		{% for form in wizard.form.forms %}
			{{form}
		{% endfor %}
	{% else %}
		{{wizard.form}}
	{% endif %}
	</table>

	<!-- check in the steps, if there is a previous step -->
	{% if wizard.steps.prev %}
	<!-- to step back to first step -->
	<button name="wizard_goto_step" type="submit" value="{{wizard.steps.first}}">"first step"</button>
	<!-- to step back to previous step -->	
	<button name="wizard_goto_step" type="submit" value="{{wizard.steps.prev}}">"prev step"</button>
	{% endif %}
	<!-- this sumbit tells the wizard to moveon to the next page -->
	<input type="submit" value="Submit"></input>
	</form>
{% endblock %}

article/templates/create_article.html
{% extends "base.html" %}
{% load staticfiles %}

{% block sidebar %}
			<ul>
				<li><a href="/articles/all">Cancel</a></li>
			</ul>
{% endblock %}

{% block container %}
	<form action="/articles/create/" method="POST" enctype="multipart/form-data">{% csrf_token %}
		<ul>
			{{form.as_ul}}
		</ul>
		<input type="submit" name="submit" value="Create Article"></input>
	<!-- "/articles/create" is a URL that takes in the create method from views.py -->
	</form>
{% endblock %}